RaceMateDB/ViewModels/PredictedResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace RaceMateDB.ViewModels
{
    public class PredictedResultViewModel
    {     

        [Display(Name = "Rider Id")]
        public int RiderID { get; set; }
        
        [Required]
        [Display(Name = "Rider Name")]
        [StringLength(75)]
        public string RiderName { get; set; }

        [Required]
        [Display(Name = "Result")]
        public string Result{ get; set; }
        public IEnumerable<SelectListItem> Results {get; set;}


        [Required]
        [Display(Name = "ResultWeighting")]
        public int ResultWeighting { get; set; }

        [Required]
        [Display(Name = "NumberOfResults")]
        public int NumberofResults { get; set; }

        [Required]
        [Display(Name = "IsEntered")]
        public bool IsEntered { get; set; }

        [Required]
        [Display(Name = "EventModelId")]
        public int EventModelId { get; set; }








    }
}

RaceMateDB/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RaceMateDB.Models;
using System.Data.Entity;
using RaceMateDB.Repositories;
using RaceMateDB.ViewModels;
using PagedList;
using System.Net;



namespace RaceMateDB.Controllers

{



    public class EventController : Controller
    {
        RMDBContext _db = new RMDBContext();

        //use a data- attribute to wire up this action
        public ActionResult Autocomplete(string term) //term is supported parameter

        {
            var model = _db.EventModels
                .Where(r => r.Name.StartsWith(term))
                .Take(10)
                .Select(r => new
                {
                    label = r.Name         //project into object with label property - autocomplete has label prop in DOM
                });

            return Json(model, JsonRequestBehavior.AllowGet);  //serialize into json
        }



        // GET: Event
        public ActionResult Index(string searchTerm, int page = 1)
        {                      
            var model = _db.EventModels
                                       .OrderByDescending(r => r.Date)
                                       .Where(r => searchTerm == null || r.Name.Contains(searchTerm))
                                       .ToPagedList(page, 15);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_Events", model);
            }
            return View(model);                                       
        }


        // GET: Courses Events
        public ActionResult CourseEvents([Bind(Prefix="id")] int courseId, int page = 1)
        {                        
            var model = _db.EventModels
                                      .OrderBy(r => r.Name)
                                     .Where(r => r.CourseId == courseId)
                                     .ToPagedList(page, 15);

           if (Request.IsAjaxRequest())

            {
              return PartialView("_Events", model);               
            }
           return View(model);

        }

        // get: event
        public ActionResult Results(int id)
        {
            var model = _db.ResultModels
                                        .OrderBy(e => e.Position)
                                        .Include(e => e.Event)
                                        .Include(e => e.Rider)
                                        .Where(i => i.EventModelId == id);

           return View(model);
          
        }

        /// <summary>
        /// /////////////////////////////////////////////
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        // get: event
        [HttpGet]
        public ActionResult PredictedResults(int id)
        {          
            var modelList = new List<PredictedResultViewModel>();

            var data = _db.ResultModels
                                        .Include(e => e.Event)
                                        .Include(e => e.Rider);

                            
            

            //Refactored code  below into PredictedResultLogic but I think this makes it harder to read?

            //Definitely harder to troubleshoot!!! Change bacK?

            foreach (var item in data)
            {
                PredictedResultLogic.GeneratePredictedResultModel(modelList, item, id);
            }
            //orderlist by predictedResults
            var orderedModelList = modelList.OrderByDescending(r => r.ResultWeighting)
                                    .Where(i => i.IsEntered == true);             //added this filter for troubleshooting.


            return View(orderedModelList);
        }

        

        /// <summary>
        /// //////////////////////////////////////////
        /// </summary>
        /// <returns></returns>

        // GET: Event/Create
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {

            var repo = new EventRepository();

            var addEventViewModel = repo.CreateEvent();

            return View(addEventViewModel);
        }

        // POST: Event/Create
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(AddEventViewModel addEventViewModel)
        {
            
            var model = new EventModel()

            {
                Name = addEventViewModel.EventName,
                Date = addEventViewModel.Date,              
                CourseId = Convert.ToInt32(addEventViewModel.SelectedCourse)  //Should I be converting this backward and forwards??

            };

            if (ModelState.IsValid)
            {
                _db.EventModels.Add(model);               
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = model.CourseId });

            }

            return View(addEventViewModel);

        }




        // GET: Event/ViewEventReview
        [HttpGet]
        public ActionResult ViewEventReview([Bind(Prefix = "id")] int id)
        {

            var model =
                    from r in _db.EventReviews
                    where (r.EventModelId== id)
                    select r;

            
            return View(model);
        }


        //// GET: Event/Comment
        //[HttpGet]
        //public ActionResult EventReview(int id)
        //{
        //    var model =
        //           from r in _db.EventReviews
        //           where (r.EventModelId == id)
        //           select r; 
        //    return View(model);
        //}

        // GET: Event/AddEventReview
       
      

    
         [HttpGet]
         public ActionResult AddEventReview(int eventModelId)
        {
            return View();
        }
 




        // POST: Event/AddEventReview
        [HttpPost]
        public ActionResult AddEventReview(EventReview eventReview)
        {
            if (ModelState.IsValid)
            {
                _db.EventReviews.Add(eventReview);
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = eventReview.EventModelId });

            }

            return View(eventReview);

        }






        //Get: /Event/Edit/5

        [HttpGet]
        public ActionResult EditEventReview(int Id)

        {
            var model = _db.EventReviews.Find(Id);
            return View(model);

        }




        //Post: /Event/Edit/5


        [HttpPost]
        public ActionResult EditEventReview(EventReview eventReview)
        {
            if (ModelState.IsValid)


            {
                _db.Entry(eventReview).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = eventReview.EventModelId });

            }
                       

            return View(eventReview);
        }






        // POST: Event/Edit
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(AddEventViewModel addEventViewModel)
        {
            if (addEventViewModel.EventId == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var model = new EventModel()

            {
                
                Id = (int)addEventViewModel.EventId,
                Name = addEventViewModel.EventName,
                Date = addEventViewModel.Date,

                //Should I be converting this backward and forwards??
                CourseId = Convert.ToInt32(addEventViewModel.SelectedCourse)

            };

            if (ModelState.IsValid)
            {
               _db.Entry(model).State = EntityState.Modified;
               _db.SaveChanges();
                return RedirectToAction("Index", new { id = model.Id});

            }

            return View(addEventViewModel);

        }



        




        // GET: EventModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var courseRepo = new CourseRepository();          
                        
            EventModel editEventModel = _db.EventModels
                                        .Include(i => i.EventResults)
                                        .Where(i => i.EventResults.FirstOrDefault().EventModelId == id)                                      
                                        .SingleOrDefault();

            AddEventViewModel addEventViewModel = new AddEventViewModel();

            if (editEventModel != null)
            {
                               

                addEventViewModel.EventId = editEventModel.EventResults.FirstOrDefault().EventModelId;
                addEventViewModel.Courses = courseRepo.GetCourses(false);
                addEventViewModel.EventName = editEventModel.Name;
                addEventViewModel.Date = editEventModel.Date;
                addEventViewModel.SelectedCourse = editEventModel.Course.Name;

            }

            return View(addEventViewModel);
                             
        }


        // GET: EventModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventModel eventModel = _db.EventModels.Find(id);
            if (eventModel == null)
            {
                return HttpNotFound();
            }
            return View(eventModel);
        }

        // POST: EventModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventModel eventModel = _db.EventModels.Find(id);
            _db.EventModels.Remove(eventModel);

RaceMateDB/Controllers/RiderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using RaceMateDB.Models;
using PagedList;
using System.Net;
using RaceMateDB.Repositories;
using RaceMateDB.ViewModels;

namespace RaceMateDB.Controllers
{
    public class RiderController : Controller
    {

        RMDBContext _db = new RMDBContext();
        
        //use a data- attribute to wire up this action
        public ActionResult Autocomplete(string term) //term is supported paramater

        {
            var model = _db.RiderModels
                .Where(r => r.Name.StartsWith(term))
                .Take(10)
                .Select(r => new     
                {
                    label = r.Name         //project into object with label property - autocomplete has label prop in DOM
                });

            return Json(model, JsonRequestBehavior.AllowGet);  //serialize into json
            
        }
        
        // GET: Rider
        public ActionResult Index(string searchTerm, int page =1)   //add default page for pagelist
        {
            //refactored into expression

            var model = _db.RiderModels                                        
                                        .OrderBy(r => r.Name)
                                        .Where(r => searchTerm == null || r.Name.Contains(searchTerm))
                                        .ToPagedList(page, 15);   //default page
            //   .Take(10);                           



            if (Request.IsAjaxRequest())

            {
                return PartialView("_Riders", model);
            }

            return View(model);

        }

        public ActionResult ViewRiderEvents(int Id)
        {
                       
            var model = _db.ResultModels.Include(e => e.Event)
                                      .Include(e => e.Rider)                                   
                                     .Where(i => i.RiderModelId == Id && i.Event.HasResult == true)
                                     .OrderByDescending(i=> i.Event.Date);

            return View(model);
                    
        }
            
        // GET: Rider/Create
        public ActionResult Create()
        {
           
            var repo = new RiderRepository();

            var riderEditViewModel = repo.EditRider(IsNew: true);

            return View(riderEditViewModel);

        }
        
        // POST: Rider/Create
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(RiderEditViewModel riderEditViewModel)
        {

            var model = new RiderModel()

            {
                Name = riderEditViewModel.RiderName,
                ClubOrTeamId = Convert.ToInt32(riderEditViewModel.SelectedClubOrTeam)
                                                            
            };

            if (ModelState.IsValid)
            {
                _db.RiderModels.Add(model);
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = model.Id});

            }

            return View(model);

        }

     
        // GET: Rider/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int Id)
        {

            var rider = _db.RiderModels.Single(r => r.Id == Id);                   
                     
            var repo = new RiderRepository();

            var riderEditViewModel = repo.EditRider(IsNew: false);

            riderEditViewModel.RiderID = rider.Id;
            riderEditViewModel.RiderName = rider.Name;
            riderEditViewModel.SelectedClubOrTeam = rider.ClubOrTeam.Name;

            return View(riderEditViewModel);
                      
            
        }


        // POST: Rider/Edit
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(RiderEditViewModel riderEditViewModel)
        {
            if (riderEditViewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new RiderModel()

            {
                Id = riderEditViewModel.RiderID,
                Name = riderEditViewModel.RiderName,
                ClubOrTeamId = Convert.ToInt32(riderEditViewModel.SelectedClubOrTeam)              
                               
            };

            if (ModelState.IsValid)
            {
                _db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = model.Id });
            }
            return View(riderEditViewModel);
        }





        // GET: RiderModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RiderModel riderModel = _db.RiderModels.Find(id);
            if (riderModel == null)
            {
                return HttpNotFound();
            }
            return View(riderModel);
        }



        // GET: RiderModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RiderModel riderModel = _db.RiderModels.Find(id);
            if (riderModel == null)
            {
                return HttpNotFound();
            }
            return View(riderModel);
        }

        // POST: RiderModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RiderModel riderModel = _db.RiderModels.Find(id);
            _db.RiderModels.Remove(riderModel);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }


            base.Dispose(disposing);

        }

    }
}

RaceMateDB/Views/Event/AddEventReview.cshtml
@model RaceMateDB.Models.EventReview

@{
    ViewBag.Title = "AddEventReview";
}

<h2>AddEventReview</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EventReview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>
    

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
  
}

RaceMateDB/Views/Event/CourseEvents.cshtml
@model IPagedList<EventModel>



<form method="get" action="@Url.Action("Index")"
      data-rmdb-ajax="true" data-rmdb-target="#eventList">

    <input type="search" name="searchTerm" data-rmdb-autocomplete="@Url.Action("Autocomplete")" />
    <input type="submit" value="Search By Name" />
</form>

@{if (Model.FirstOrDefault() != null)
        {@Html.Partial("_Events", Model)}
    else
    {<h2> Sorry, there are no events for this course...Please check back later... </h2>}
    }



   

RaceMateDB/Views/Event/Create.cshtml
@model RaceMateDB.ViewModels.AddEventViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Event</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedCourse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedCourse, new SelectList(Model.Courses, "Value", "Text"), htmlAttributes: new { @class = "form-control", id = "Course" })
                @Html.ValidationMessageFor(model => model.SelectedCourse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Date", String.Format("{0:d}", Model.Date),new { @class = "datefield", type = "Date" })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>

        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



@section Scripts {



}

RaceMateDB/Views/Event/Delete.cshtml
@model RaceMateDB.Models.EventModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HasResult)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HasResult)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RaceMateDB/Views/Event/Edit.cshtml
@model RaceMateDB.ViewModels.AddEventViewModel

@{
    ViewBag.Title = "Edit";
}




@if (Model.EventName != null)
{

    <h2>Edit</h2>

    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>EventModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.EventId)

            <div class="form-group">
                @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.SelectedCourse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SelectedCourse, new SelectList(Model.Courses, "Value", "Text"), Model.SelectedCourse, htmlAttributes: new { @class = "form-control", id = "Course" }) @*Show existing info and resubmit if unchanged.*@


                    @Html.ValidationMessageFor(model => model.SelectedCourse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.TextBox("Date", String.Format("{0:d}", Model.Date),
                        Model.Date )*@



                    @Html.TextBox("Date", String.Format("{0:yyyy-MM-dd}", Model.Date),   //Set DateTime format so it can be displayed and edited. "{0:yyyy-MM-dd}"
         new { @class = "datefield", type = "Date" })


                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

}

else

{
    <h2> Sorry, there is no data associated with this event... </h2>
}

@section Scripts {

}

RaceMateDB/Views/Event/EditEventReview.cshtml
@model RaceMateDB.Models.EventReview

@{
    ViewBag.Title = "EditEventReview";
}

<h2>EditEventReview</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EventReview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

     

        @Html.HiddenFor(model => model.EventModelId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
  
}

RaceMateDB/Views/Event/Index.cshtml
@model IPagedList<EventModel>



@{
    ViewBag.Title = "Events";
}

<h2>Events</h2>


<form method="get" action="@Url.Action("Index")"
      data-rmdb-ajax="true" data-rmdb-target="#eventList">

    <input type="search" name="searchTerm" data-rmdb-autocomplete="@Url.Action("Autocomplete")" />
    <input type="submit" value="Search By Name" />
</form>


<br />




@Html.Partial("_Events", Model)

RaceMateDB/Views/Event/PredictedResults.cshtml
@model IEnumerable<RaceMateDB.ViewModels.PredictedResultViewModel>

@{
    ViewBag.Title = "PredictedResults";
}





@{if (Model.FirstOrDefault() != null)
    {

        <h2>PredictedResults</h2>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RiderName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberofResults)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ResultWeighting)
                </th>

                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RiderName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberofResults)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ResultWeighting)
                    </td>
                    <td>
                        | @Html.ActionLink("Rider Results", "ViewRiderEvents", "Rider", new { id = item.RiderID }, null) |
                    </td>
                </tr>
            }

        </table>

    }

    else
    {
        <h2> Sorry, no  one has entered this event yet... Please check back later... </h2>
    }


}

RaceMateDB/Views/Event/_Riderresults.cshtml
@model RaceMateDB.Models.RiderModel




@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
  </tr>
}

RaceMateDB/Views/Event/results.cshtml
@model IEnumerable<ResultModel>

@{
    ViewBag.Title = "results";

}




<div class="displayedResult">

    @{if (Model.FirstOrDefault() != null)

        {
            <h2> Results for @Model.First().Event.Name </h2>




            <table class="table">
                <tr>


                    <th>
                        @Html.DisplayNameFor(model => model.Position)
                    </th>

                    <th>
                        Rider
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>


                        <td>
                            @Html.DisplayFor(modelItem => item.Position)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Rider.Name)

                        </td>

                        <td>
                            | @Html.ActionLink("View Riders Results", "ViewRiderEvents", "Rider", new { id = item.RiderModelId }, null) |
                            @if (@User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) <text>|</text>
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id }) <text>|</text>
                            }
                        </td>
                    </tr>
                }

            </table>













        }




        else

        {
            <h2> Sorry, there are no results for this event... Please check back later... </h2>
        }
    }



</div>


<script>
        var positionList = document.querySelector(".displayedResult");

        positionList = (positionList.firstElementChild.nextElementSibling.firstElementChild.children);

    Array.from(positionList).forEach(function (item) {

        var riderPosition = item.firstElementChild.textContent;       

        if (riderPosition == 1) {

         

            item.firstElementChild.innerHTML = ('<span class="icon-1"></span>');
           
        }


        if (riderPosition == 2) {

         

            item.firstElementChild.innerHTML = ('<span class="icon-2"></span>');

        }

        if (riderPosition == 3) {

            

            item.firstElementChild.innerHTML = ('<span class="icon-3"></span>');

        }
    
    });   
</script>